services:
  mock_database:
    image: postgres
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: 12345
    volumes:
      - ./.volume/db-data/user_db/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d 12345"]
      interval: 5s
      timeout: 5s
      retries: 5